# GeyserMenu 配置文件
# 作者: 柠枺
# 版本: 1.0.1

# 插件设置
settings:
  # 默认菜单文件名
  default-menu: "menu.yml"
  
  # 调试模式
  debug: false

# 菜单配置
menus:
  # 主菜单
  main:
    file: "menu.yml"
    enable: true
  
  # 传送菜单
  teleport:
    file: "teleport.yml"
    enable: true
  
  # 商店菜单
  shop:
    file: "shop.yml"
    enable: true
  
  # 示例：禁用的菜单
  example:
    file: "example.yml"
    enable: false

# 图标设置
icons:
  # 自定义图标目录
  custom_path: "plugins/GeyserMenu/icons"
  
  # 是否允许URL图标
  allow_url: true
  
  # 默认图标
  default: "minecraft:paper"